// //Types for Login
// export const LOGIN_REQUEST_REQUEST = 'LOGIN_REQUEST_REQUEST';
// export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
// export const LOGIN_REQUEST_FAILURE = 'LOGIN_REQUEST_FAILURE';
// //Types for Logout
// export const LOGOUT_REQUEST_REQUEST = 'LOGOUT_REQUEST_REQUEST';
// export const LOGOUT_REQUEST_SUCCESS = 'LOGOUT_REQUEST_SUCCESS';
// export const LOGOUT_REQUEST_FAILURE = 'LOGOUT_REQUEST_FAILURE';
// //Types for Social Login
// export const SOCIAL_LOGIN_REQUEST_REQUEST = 'SOCIAL_LOGIN_REQUEST_REQUEST';
// export const SOCIAL_LOGIN_REQUEST_SUCCESS = 'SOCIAL_LOGIN_REQUEST_SUCCESS';
// export const SOCIAL_LOGIN_REQUEST_FAILURE = 'SOCIAL_LOGIN_REQUEST_FAILURE';
// //Types for Sign up
// export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
// export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
// export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

// //Types for OTP Verification
// export const OTP_VERIFY_REQUEST = 'OTP_VERIFY_REQUEST';
// export const OTP_VERIFY_SUCCESS = 'OTP_VERIFY_SUCCESS';
// export const OTP_VERIFY_FAILURE = 'OTP_VERIFY_FAILURE';

// //Types for  forgot password
// export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
// export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
// export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';

// //Types for reset password
// export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
// export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
// export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

// //Types for Walkthrough
// export const SET_WALKTHROUGH_REQUEST = 'SET_WALKTHROUGH_REQUEST';
// export const SET_WALKTHROUGH_SUCCESS = 'SET_WALKTHROUGH_SUCCESS';

// //SET PROFILE IMAGE
// export const SET_PROFILE_IMAGE = 'SET_PROFILE_IMAGE';
// export const SET_PROFILE_IMAGE_REQUEST = 'SET_PROFILE_IMAGE_REQUEST';

// //GET PROFILE
// export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
// export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
// export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';

// //UPDATE PROFILE
// export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
// export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
// export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';

// //GET PRIVACY POLICY
// export const GET_PRIVACY_POLICY_REQUEST = 'GET_PRIVACY_POLICY_REQUEST';
// export const GET_PRIVACY_POLICY_SUCCESS = 'GET_PRIVACY_POLICY_SUCCESS';
// export const GET_PRIVACY_POLICY_FAILURE = 'GET_PRIVACY_POLICY_FAILURE';

// //GET FAQ's
// export const GET_FAQ_REQUEST = 'GET_FAQ_REQUEST';
// export const GET_FAQ_SUCCESS = 'GET_FAQ_SUCCESS';
// export const GET_FAQ_FAILURE = 'GET_FAQ_FAILURE';

// //GET TERMS & CONDITIONS
// export const GET_TERMS_CONDITION_REQUEST = 'GET_TERMS_CONDITION_REQUEST';
// export const GET_TERMS_CONDITION_SUCCESS = 'GET_TERMS_CONDITION_SUCCESS';
// export const GET_TERMS_CONDITION_FAILURE = 'GET_TERMS_CONDITION_FAILURE';
